
providers = ["php"]


[phases.setup]
nixPkgs = ["php83", "php83Packages.composer"]


[phases.build]
cmds = ["composer install --no-interaction --prefer-dist --optimize-autoloader"]


[start]
cmd = "vendor/bin/heroku-php-apache2 public/"
